CalendarAPI/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('auth/', include('accounts.urls')),
    path('events/', include('events.urls')),
]

accounts/urls.py
from django.urls import path
from .views import Register_Users, User_logout, login_user, login_u, register_u

app_name = 'users'
urlpatterns = [
   path('login', login_u, name="login"),
   path('register', register_u, name="register"),
   path('api/register_user/', Register_Users, name="register_api"),
   path('api/login_user/', login_user, name="login_api"),
   path('api/logout_user/', User_logout, name="logout_api")
]

events/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import ListEvents, CreateEvent, addEventView, indexView, indexViewByMonth

app_name = 'events'

urlpatterns = [
    path('api/list/', ListEvents, name="list_events"),
    #path('api/list/month<int:num>', ListEvents, name="list_events_month"),
    path('api/create/', CreateEvent, name="create_event"),
    path('', indexView, name="index"),
    path('add', addEventView, name="add_event")
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager

class CustomAccountManager(BaseUserManager):
    def create_user(self, email, username, name, password, **other_fields):
        if not email:
            raise ValueError('Users must have an email address')
        
        user = self.model(
            email_adress = self.normalize_email(email),
            name = name,
            username = username,
            **other_fields
        )
        
        user.set_password(password)
        user.save(using=self._db)
        
        return user
        
    def create_superuser(self, email, username, name, password, **other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)
        
        if other_fields.get('is_staff') is not True:
            raise ValueError('Please assign is_staff=True for superuser')
        if other_fields.get('is_superuser') is not True:
            raise ValueError('Please assign is_superuser=True for superuser')
        
        return self.create_user(email, username, name, password, **other_fields)

class Users(AbstractBaseUser):
    email_address = models.EmailField(verbose_name="email", max_length=60, unique=True, blank=True, default=None)
    name = models.CharField(max_length=30, blank=True, null=True, default=None)
    username = models.CharField(max_length=30, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    
    USERNAME_FIELD = 'email_address'
    
    objects=CustomAccountManager()
    
    class Meta:
        db_table = "tbl_users"
        
    def __str__(self):
        return str(self.email_address)

    def has_perm(self, perm, obj=None): return self.is_superuser

    def has_module_perms(self, app_label): return self.is_superuser

accounts/views.py
from django.forms import ValidationError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import login, logout
from django.contrib.auth.hashers import check_password
from django.urls import reverse_lazy
from psycopg2 import IntegrityError
from rest_framework import status
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.decorators import api_view, permission_classes
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from .models import Users
from .serializers import RegistrationSerializer
import json

@api_view(["POST"])
@permission_classes([AllowAny])
def Register_Users(request):
    try:
        data = {}
        serializer = RegistrationSerializer(data=request.data)
        if serializer.is_valid():
            account = serializer.save()
            account.is_active = True
            account.save()
            token = Token.objects.get_or_create(user=account)[0].key
            data["message"] = "user registered successfully"
            data["email"] = account.email_address
            data["username"] = account.username
            data["token"] = token
        else:
            data = serializer.errors
        #response = Response(data, status=status.HTTP_201_CREATED)
        
        return HttpResponseRedirect(redirect_to=reverse_lazy('users:login'))
    except IntegrityError as e:
        account=Users.objects.get(username='')
        account.delete()
        raise ValidationError({"400": f'{str(e)}'})
    
    except KeyError as e:
        print(e)
        raise ValidationError({"400": f'Field {str(e)} missing'})
    
@api_view(["POST"])   
@permission_classes([AllowAny])
def login_user(request):
    data = {}
    #reqBody = json.loads(request.body)
    email = request.POST['email']
    password = request.POST['password'] 
    try:
        account = Users.objects.get(email_address=email)
    except BaseException as e:
        raise ValidationError({"400": f'{str(e)}'}) 
    
    token = Token.objects.get_or_create(user=account)[0].key
    if not check_password(password, account.password):
        raise ValidationError({"message": "Incorrect Login Credentials"})
    
    if account:
        if account.is_active:
            login(request, account)
            data["message"] = "user logged in"
            data["email_address"] = account.email_address
            data["token"] = token
            response = HttpResponseRedirect(redirect_to=reverse_lazy('events:index'))
            response.set_cookie('access_token', token)
            return response
        else:
            raise ValidationError({"404": f'Account not active'})
    else:
        raise ValidationError({"400": f'Account doesnt exist'})
            
@api_view(["GET"])
@permission_classes([IsAuthenticated])
def User_logout(request):
    response = Response('User Logged out successfully')
    response.delete_cookie('access_token')
    request.user.auth_token.delete()
    logout(request)
    return response

def login_u(request):
    return render(request, 'login.html')

def register_u(request):
    return render(request, 'register.html')

    
    
    
    
    
    
#  {
# "email_address":"test@gmail.com",
# "username":"khabib",
# "password":"1234",
# "name":"bibib"
# }

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Django{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light"> 
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Calendar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" aria-current="page" href="{% url 'events:index' %}">Events</a>
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
            <a class="nav-link" href="{% url 'events:add_event' %}">Add event</a>
            <button class="btn btn-light" style="float: right" onclick="logout_user()">Logout</button>
          </div>
        </div>
      </div>
    </nav>
    
    {% block content %}{% endblock %}
    <script>
        function logout_user(){
            var url = "{% url 'users:logout_api' %}";

            var xhr = new XMLHttpRequest();
            xhr.open("GET", url);
            
            xhr.setRequestHeader("Authorization", "token " + getCookie('access_token'));
            
            xhr.onreadystatechange = function () {
               if (xhr.readyState === 4) {
                  console.log(xhr.status);
                  console.log(xhr.responseText);
               }
            };
            
            xhr.send();
            setTimeout(() => {
                location.replace("{% url 'users:login' %}");
              }, 2000)
            
        }

        function getCookie(cname) {
            let name = cname + "=";
            let decodedCookie = decodeURIComponent(document.cookie);
            let ca = decodedCookie.split(';');
            for(let i = 0; i <ca.length; i++) {
              let c = ca[i];
              while (c.charAt(0) == ' ') {
                c = c.substring(1);
              }
              if (c.indexOf(name) == 0) {
                return c.substring(name.length, c.length);
              }
            }
            return "";
          }
    </script>
    {% block script %}
    {% endblock %}
</body>

accounts/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
    <form action={% url 'users:login_api' %} method="post" style='width: 15%' class="p-2">
        <label for="email" class="form-label">Email:</label>
        <input type="email" class="form-control mb-1" name="email" id="email" required>
        <label for="password" class="form-label">Password:</label>
        <input type="password" class="form-control" name="password" id="password" required>
        <input type="submit" class="btn btn-primary mt-2" value="Login">
    </form>
    <br></br>
{% endblock %}

accounts/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block content %}
    <form action={% url 'users:register_api' %} method="post" style='width: 15%' class="p-2">
        <label for="email_address" class="form-label">Email:</label>
        <input type="email" class="form-control" name="email_address" id="email_address" required>
        <label for="username" class="form-label">Username:</label>
        <input type="text" class="form-control" name="username" id="username" required>
        <label for="name" class="form-label">Name:</label>
        <input type="text" class="form-control" name="name" id="name" required>
        <label for="password" class="form-label">Password:</label>
        <input type="password" class="form-control" name="password" id="password" required>
        <input type="submit" class="btn btn-primary mt-2" value="Register">
    </form>
    <br></br>
{% endblock %}