CalendarAPI/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('auth/', include('accounts.urls')),
    path('events/', include('events.urls')),
]

events/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import ListEvents, CreateEvent, addEventView, indexView, indexViewByMonth

app_name = 'events'

urlpatterns = [
    path('api/list/', ListEvents, name="list_events"),
    #path('api/list/month<int:num>', ListEvents, name="list_events_month"),
    path('api/create/', CreateEvent, name="create_event"),
    path('', indexView, name="index"),
    path('add', addEventView, name="add_event")
]

events/models.py
from django.db import models
from accounts import models as accounts_model

class Event(models.Model):
    user = models.ForeignKey(accounts_model.Users, verbose_name="User", on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField() 
    ReminderTime = models.DateTimeField() 
    

events/views.py
from ast import Not
from audioop import reverse
from datetime import timedelta, datetime
from email.policy import default
import json
from django.urls import reverse_lazy
import requests
from requests.structures import CaseInsensitiveDict
from django.shortcuts import render
from django.utils import timezone
from rest_framework import status
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.decorators import api_view, permission_classes
from rest_framework.authtoken.models import Token
from accounts.models import Users
from .serializers import EventListSerializer
import time
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
import smtplib
import os

@api_view(['GET'])
@permission_classes([IsAuthenticated])
def ListEvents(request):
    access_token = request.headers['Authorization'][6:]
    user_id = Token.objects.get(key=access_token).user_id
    user = Users.objects.get(id=user_id)
    month = request.GET.get('month', None)
    if month is None:
        events = user.event_set.order_by('start_date')
    else:
        events = user.event_set.filter(start_date__month = month)
    
    serializer = EventListSerializer(events, many=True) 
    return Response(serializer.data)


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def CreateEvent(request):
    data = {}
    reqBody = json.loads(request.body)
    access_token = request.headers['Authorization'][6:]
    user_id = Token.objects.get(key=access_token).user_id
    user = Users.objects.get(pk=user_id)
    data['user'] = user_id
    data["message"] = "event created successfully"
    data["name"] = reqBody.get('name')
    data["start_date"] = reqBody.get('start_date', timezone.now())
    data["end_date"] = reqBody.get('end_date', timezone.now().replace(hour=23, minute=59, second=59, microsecond=999999))
    data["ReminderTime"] = reqBody.get('reminder_time')
    serializer = EventListSerializer(data=data)
    if serializer.is_valid():
        event = serializer.save()
        event.save()
        data["message"] = "event created successfully"
        mail(event.name, user.email_address, event.ReminderTime)
        
        return Response(data, status=status.HTTP_201_CREATED)
    else:
        data = serializer.errors
        return Response(data)
    
def indexView(request):
    month_num = request.GET.get('month', None)
    month_add = '' if month_num is None else f'?month={month_num}'
    url = request.scheme + '://' + request.META['HTTP_HOST'] + reverse_lazy('events:list_events') + month_add
    access_token = request.COOKIES.get('access_token', None)
    if access_token is None:
        return render(request, 'restricted.html')
    else:
        headers = CaseInsensitiveDict()
        headers["Authorization"] = "token " + access_token

        resp = requests.get(url, headers=headers)
        content = resp.content.decode("utf-8")
        events = json.loads(content)
        print(events)
        return render(request, 'index.html', {"events" : events})

def indexViewByMonth(request, num=1):
    url = request.scheme + '://' + request.META['HTTP_HOST'] + reverse_lazy('events:list_events')
    access_token = request.COOKIES.get('access_token', None)
    if access_token is None:
        return render(request, 'restricted.html')
    else:
        headers = CaseInsensitiveDict()
        headers["Authorization"] = "token " + access_token
        
        resp = requests.get(url, headers=headers)
        content = resp.content.decode("utf-8")
        events = json.loads(content)
        print(events)
        return render(request, 'index.html', {"events" : events})
    
def addEventView(request):
    return render(request, 'addEvent.html')
    
def mail(event_name, user_address, send_time):
    smtp = smtplib.SMTP('smtp.gmail.com', 587)
    smtp.ehlo()
    smtp.starttls()
    smtp.login('alihangames1@gmail.com', 'UzumakiAlikhan')
    msg = message(event_name)
    to = [user_address]
    send_time = datetime.fromisoformat(send_time.isoformat())
    time.sleep(send_time.timestamp() - time.time())
    smtp.sendmail(from_addr="alihangames1@gmail.com",
                to_addrs=to, msg=msg.as_string())
    smtp.quit()

def message(text=""):
	msg = MIMEMultipart()
	msg['Subject'] = "Calendar Notification"
	msg.attach(MIMEText(text))

	return msg

events/templates/addEvent.html
{% extends "base.html" %}
{% block title %}Add Event{% endblock %}
{% block content%}
{% csrf_token %}
<form method="POST" class="p-2">
    <div class="row">
        <div class="col-3">
            <label for="name"  class="form-label">Name:</label>
            <input type="text" class="form-control" name="name" id="name" required>
            <label for="start_date" class="form-label">Choose a time for start of your event:</label>
            <input type="datetime-local" class="form-control" id="start_date" name="start_date" required>
            <label for="end_date" class="form-label">Choose a time for end of your event:</label>
            <input type="datetime-local" class="form-control" id="end_date" name="end_date">
        </div>
        <div class="col-4">
            <fieldset>
            <legend>Select a time to reminder:</legend>
                <div>
                <input type="radio" class="form-check-input" id="hour" name="reminder" value="1"
                        checked>
                <label for="hour">Hour before</label>
                </div>

                <div>
                <input type="radio" class="form-check-input" id="two_hour" name="reminder" value="2">
                <label for="two_hour">Two hour before</label>
                </div>

                <div>
                <input type="radio" class="form-check-input" id="four_hour" name="reminder" value="4">
                <label for="four_hour">Four hour before</label>
                </div>

                <div>
                    <input type="radio" class="form-check-input" id="day" name="reminder" value="24">
                    <label for="day">Day before</label>
                </div>

                <div>
                    <input type="radio" class="form-check-input" id="week" name="reminder" value="168">
                    <label for="week">Week before</label>
                </div>

            </fieldset>
        </div>
    </div>
</form>
<button onclick="add_event()">Add Event</button>
{% endblock %}
{% block script%}
<script>
    function add_event(){
        let name = document.querySelector('#name').value
        let start_date = document.querySelector('#start_date').value;
        let end_date = document.querySelector('#end_date').value
        let reminder_time = document.querySelector('input[name="reminder"]:checked').value;
        let s_date = new Date(start_date)
        let reminder_date = reduceHours(reminder_time, s_date)
        var url = "{% url 'events:create_event' %}";
        if(start_date == end_date){
            alert('start_date should not be equal to end_date')
            return null
        }
        if (start_date == ''){
            alert('Select start date')
        }
        if (end_date == ''){
            end_of_day = new Date()
            end_date_sec = end_of_day.setUTCHours(23, 59, 59);
            end_date = new Date(end_date_sec).toISOString()
        }
        var xhr = new XMLHttpRequest();
        xhr.open("POST", url);

        xhr.setRequestHeader("Authorization", "token " + getCookie('access_token'));
        xhr.setRequestHeader("Content-Type", "application/json");

        xhr.onreadystatechange = function () {
            if (xhr.readyState === 4) {
                console.log(xhr.status);
                console.log(xhr.responseText);
            }
        };

        var data = `{
            "name": "${name}",
            "start_date": "${start_date}",
            "end_date": "${end_date}",
            "reminder_time": "${reminder_date.toISOString()}"
        }`;

        xhr.send(data);
        
        setTimeout(() => {
            location.replace("{% url 'events:index' %}");
          }, 2000)
    }

    function reduceHours(numOfHours, date = new Date()) {
        date.setTime(date.getTime() - numOfHours * 60 * 60 * 1000);
      
        return date;
    }
</script>
{% endblock%}

events/templates/index.html
{% extends "base.html" %}
{% block title %}Events{% endblock %}

{% block content %}
<body>
    <h1>List of Events</h1>
    <ul>
    {% for event in events  %}
        <li>{{event.name}}</li>
        <ul>
            <li>start_date {{event.start_date}}</li>
            <li>end_date {{event.end_date}}</li>
            <li>reminder_date {{event.ReminderTime}}</li>
        </ul>
    {% endfor %}
    </ul>
{% endblock %}

events/templates/restricted.html
{% extends "base.html" %}
{% block title %}Restricted{% endblock %}
{% block content%}
<h1>Log In first</h1>
{% endblock %}